"""initial_schema

Revision ID: b2618c74dc5a
Revises: 
Create Date: 2026-05-29 16:11:33.700678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2618c74dc5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churn_scores',
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=8), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('score_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('churn_probability', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('risk_tier', sa.String(length=10), nullable=False),
    sa.Column('feature_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('scoring_trigger', sa.String(length=30), nullable=True),
    sa.Column('prediction_horizon_days', sa.Integer(), server_default='90', nullable=False),
    sa.Column('intervention_applied', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('intervention_type', sa.String(length=50), nullable=True),
    sa.Column('post_intervention_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('score_delta', sa.Numeric(precision=5, scale=3), sa.Computed('COALESCE(post_intervention_score, churn_probability) - churn_probability', persisted=True), nullable=True),
    sa.CheckConstraint("entity_type IN ('CUSTOMER', 'EMPLOYEE')", name='ck_churn_scores_entity_type'),
    sa.CheckConstraint("risk_tier IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='ck_churn_scores_risk_tier'),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_index('idx_churn_entity', 'churn_scores', ['entity_type', 'entity_id', 'score_timestamp'], unique=False, postgresql_ops={'score_timestamp': 'DESC'})
    op.create_index('idx_churn_tier', 'churn_scores', ['risk_tier', 'score_timestamp'], unique=False, postgresql_ops={'score_timestamp': 'DESC'})
    op.create_table('feature_store',
    sa.Column('feature_record_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=8), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_days', sa.Integer(), server_default='90', nullable=False),
    sa.Column('total_calls_window', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inbound_call_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outbound_call_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_call_duration_seconds', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('escalation_frequency', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('escalation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sentiment_first_call', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sentiment_last_call', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sentiment_degradation_slope', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sentiment_std_dev', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_sentiment_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('min_sentiment_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('negative_call_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('hesitation_marker_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('filler_word_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('anger_emotion_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('complaint_mention_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recurrence_complaint_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('avg_time_to_resolution_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('time_to_resolution_std_dev', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('max_time_to_resolution_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('dispatch_cancellation_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rescheduling_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('open_ticket_age_days_avg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('open_ticket_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('p1_p2_job_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('same_issue_recurrence_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('technician_change_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payment_delay_days_avg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('payment_failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('days_since_last_positive_call', sa.Integer(), nullable=True),
    sa.Column('days_since_last_service', sa.Integer(), nullable=True),
    sa.Column('contract_days_until_renewal', sa.Integer(), nullable=True),
    sa.Column('customer_rating_avg_90d', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('equipment_age_years', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('warranty_expired', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('complaint_rate_90d', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_customer_rating_90d', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('schedule_conflict_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('overtime_hours_90d', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('internal_escalation_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('feature_vector', pgvector.sqlalchemy.vector.VECTOR(dim=64), nullable=True),
    sa.CheckConstraint("entity_type IN ('CUSTOMER', 'EMPLOYEE')", name='ck_feature_store_entity_type'),
    sa.PrimaryKeyConstraint('feature_record_id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'window_end', 'window_days', name='uq_feature_store_entity_window')
    )
    op.create_index('idx_features_entity', 'feature_store', ['entity_type', 'entity_id', 'computed_at'], unique=False, postgresql_ops={'computed_at': 'DESC'})
    op.create_table('technicians',
    sa.Column('technician_id', sa.UUID(), nullable=False),
    sa.Column('employee_number', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('employment_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('tenure_years', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('certifications', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('service_zones', postgresql.ARRAY(sa.String(length=20)), nullable=True),
    sa.Column('avg_customer_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('jobs_completed_90d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('complaints_received_90d', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scheduled_jobs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('churn_risk_score', sa.Numeric(precision=4, scale=3), server_default='0.0', nullable=False),
    sa.Column('churn_risk_tier', sa.String(length=10), server_default='LOW', nullable=False),
    sa.Column('hr_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("churn_risk_tier IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='ck_technicians_churn_risk_tier'),
    sa.CheckConstraint("employment_status IN ('ACTIVE','ON_LEAVE','TERMINATED','PROBATION')", name='ck_technicians_employment_status'),
    sa.PrimaryKeyConstraint('technician_id'),
    sa.UniqueConstraint('employee_number')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_primary', sa.String(length=20), nullable=False),
    sa.Column('phone_secondary', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('account_status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('customer_since', sa.Date(), nullable=False),
    sa.Column('contract_type', sa.String(length=30), nullable=True),
    sa.Column('contract_value_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('preferred_tech_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_status IN ('ACTIVE','SUSPENDED','CHURNED','PROSPECT')", name='ck_customers_account_status'),
    sa.CheckConstraint("contract_type IN ('ANNUAL_MAINTENANCE','RESIDENTIAL_OTC','COMMERCIAL_SLA')", name='ck_customers_contract_type'),
    sa.ForeignKeyConstraint(['preferred_tech_id'], ['technicians.technician_id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('idx_customers_churn_risk', 'customers', [sa.text("(metadata->>'churn_tier')")], unique=False)
    op.create_index('idx_customers_phone', 'customers', ['phone_primary'], unique=False)
    op.create_index('idx_customers_status', 'customers', ['account_status'], unique=False)
    op.create_table('call_transcripts',
    sa.Column('transcript_id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('technician_id', sa.UUID(), nullable=True),
    sa.Column('dispatch_job_id', sa.UUID(), nullable=True),
    sa.Column('call_direction', sa.String(length=8), server_default='INBOUND', nullable=False),
    sa.Column('call_start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('call_end_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_outcome', sa.String(length=50), nullable=True),
    sa.Column('transcript_raw', sa.Text(), nullable=True),
    sa.Column('transcript_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_overall', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sentiment_trajectory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dominant_intent', sa.String(length=50), nullable=True),
    sa.Column('intent_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('entities_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('escalation_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('hesitation_markers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emotion_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('churn_risk_at_call_start', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('churn_risk_at_call_end', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('intervention_successful', sa.Boolean(), nullable=True),
    sa.Column('rag_queries_issued', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rag_chunks_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vapi_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("call_direction IN ('INBOUND', 'OUTBOUND')", name='ck_call_transcripts_call_direction'),
    sa.CheckConstraint("call_outcome IN ('DISPATCHED','FAQ_RESOLVED','ESCALATED_HUMAN','ABANDONED','RETAINED','VOICEMAIL')", name='ck_call_transcripts_call_outcome'),
    sa.CheckConstraint('sentiment_overall IS NULL OR (sentiment_overall >= -1 AND sentiment_overall <= 1)', name='ck_call_transcripts_sentiment_overall'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['dispatch_job_id'], ['dispatch_jobs.job_id'], name='fk_call_transcripts_dispatch_job_id', use_alter=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.technician_id'], ),
    sa.PrimaryKeyConstraint('transcript_id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index('idx_transcripts_customer', 'call_transcripts', ['customer_id'], unique=False)
    op.create_index('idx_transcripts_intervention', 'call_transcripts', ['intervention_successful'], unique=False, postgresql_where=sa.text('intervention_successful = TRUE'))
    op.create_index('idx_transcripts_outcome', 'call_transcripts', ['call_outcome'], unique=False)
    op.create_index('idx_transcripts_start', 'call_transcripts', ['call_start_utc'], unique=False, postgresql_ops={'call_start_utc': 'DESC'})
    op.create_table('equipment',
    sa.Column('equipment_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('equipment_type', sa.String(length=50), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('service_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('age_years', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('efficiency_rating', sa.String(length=20), nullable=True),
    sa.Column('known_issues', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('manual_url', sa.String(length=500), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("equipment_type IN ('AC_UNIT','FURNACE','HEAT_PUMP','AIR_HANDLER','MINI_SPLIT','OTHER')", name='ck_equipment_equipment_type'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('equipment_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('dispatch_jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('job_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('equipment_id', sa.UUID(), nullable=True),
    sa.Column('technician_id', sa.UUID(), nullable=True),
    sa.Column('call_transcript_id', sa.UUID(), nullable=True),
    sa.Column('job_status', sa.String(length=20), server_default='SCHEDULED', nullable=False),
    sa.Column('priority', sa.String(length=2), server_default='P3', nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('scheduled_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_completion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('parts_used', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('labor_hours', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('invoice_amount_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('customer_rating', sa.SmallInteger(), nullable=True),
    sa.Column('customer_feedback', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=20), server_default='VOICE_AGENT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_status IN ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','RESCHEDULED')", name='ck_dispatch_jobs_job_status'),
    sa.CheckConstraint("priority IN ('P1','P2','P3','P4')", name='ck_dispatch_jobs_priority'),
    sa.CheckConstraint('customer_rating IS NULL OR (customer_rating >= 1 AND customer_rating <= 5)', name='ck_dispatch_jobs_customer_rating'),
    sa.ForeignKeyConstraint(['call_transcript_id'], ['call_transcripts.transcript_id'], name='fk_dispatch_jobs_call_transcript_id', use_alter=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.technician_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('job_number')
    )
    op.create_index('idx_jobs_customer', 'dispatch_jobs', ['customer_id'], unique=False)
    op.create_index('idx_jobs_status', 'dispatch_jobs', ['job_status'], unique=False)
    op.create_index('idx_jobs_tech', 'dispatch_jobs', ['technician_id', 'scheduled_window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_tech', table_name='dispatch_jobs')
    op.drop_index('idx_jobs_status', table_name='dispatch_jobs')
    op.drop_index('idx_jobs_customer', table_name='dispatch_jobs')
    op.drop_table('dispatch_jobs')
    op.drop_table('equipment')
    op.drop_index('idx_transcripts_start', table_name='call_transcripts', postgresql_ops={'call_start_utc': 'DESC'})
    op.drop_index('idx_transcripts_outcome', table_name='call_transcripts')
    op.drop_index('idx_transcripts_intervention', table_name='call_transcripts', postgresql_where=sa.text('intervention_successful = TRUE'))
    op.drop_index('idx_transcripts_customer', table_name='call_transcripts')
    op.drop_table('call_transcripts')
    op.drop_index('idx_customers_status', table_name='customers')
    op.drop_index('idx_customers_phone', table_name='customers')
    op.drop_index('idx_customers_churn_risk', table_name='customers')
    op.drop_table('customers')
    op.drop_table('technicians')
    op.drop_index('idx_features_entity', table_name='feature_store', postgresql_ops={'computed_at': 'DESC'})
    op.drop_table('feature_store')
    op.drop_index('idx_churn_tier', table_name='churn_scores', postgresql_ops={'score_timestamp': 'DESC'})
    op.drop_index('idx_churn_entity', table_name='churn_scores', postgresql_ops={'score_timestamp': 'DESC'})
    op.drop_table('churn_scores')
    # ### end Alembic commands ###
